package com.tim.hundreds

enum Genre {
  BLUES, DUB, PSYCHO, BREAKBEAT, TANGO, TECHNO, AMBIENT, ELECTRO, TRIBAL, SYNTHPOP, DOWNTEMPO, CHILLOUT, CLASSICAL, LOUNGE, REGGAE, GROOVE, PROGRESSIVE, TRANCE, JAZZ, BALAD
}
